name: cs6476p6
channels:
- pytorch
- menpo
- defaults
dependencies:
- jupyter
- matplotlib
- python=3.5
- scikit-learn
- scikit-image
- scipy
- numpy
- opencv3
- cyvlfeat
- pytorch-cpu
- torchvision-cpu
- pip
- pip:
  - visdom
- pyyaml
