name: cs6476p4
channels:
- pytorch
- menpo
- defaults
dependencies:
- jupyter
- matplotlib
- python=3.5
- scikit-learn
- scipy
- opencv3
- cyvlfeat
- pytorch-cpu
- pip
- pip:
  - visdom
  - torchvision
- pyyaml
